name: Build & Analyze Backend

on:
  push:
    branches:
      - main

jobs:
  sonar-backend:
    name: SonarQube Analysis - Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Backend
        run: |
          cd 9antrakidsFormationBack
          chmod +x mvnw
          ./mvnw clean compile -DskipTests

      - name: Debug - Check compiled classes
        run: |
          ls -l 9antrakidsFormationBack/target/classes

      - name: Run SonarQube Scan (Backend)
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectKey: E-9antraKids-Backend
          projectName: "E-9antraKids Backend"
          projectVersion: 1.0
          projectBaseDir: 9antrakidsFormationBack
          sources: 9antrakidsFormationBack/src
          binaries: 9antrakidsFormationBack/target/classes
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
